services:
  - type: web
    name: aws-project-backend
    env: node
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: ap-south-1
      - key: S3_BUCKET_NAME
        value: blog-bucketss
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
